#! /bin/bash

available()
{
    type $1 > /dev/null 2>&1
}

runmake()
{
    if available gmake
    then
        gmake "$@"
    elif available make
    then
        make "$@"
    else
        echo "Please install GNU make."
        exit 1
    fi
}

for target in "$@"
do
    if [ "$target" = "clean" ]
    then
        continue
    fi
    if ! printf '%s' "$target" | grep -qE '^[0-9]+(-optimized)?-topics$'
    then
        echo "error: $target"
        echo "  use: $0 n-topics OR $0 n-optimized-topics"
        exit 1
    fi
done

time runmake "$@"
